/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_sig_sig */

#ifndef _Included_src_sig_sig
#define _Included_src_sig_sig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_sig_sig
 * Method:    importPkey
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_src_sig_sig_importPkey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     src_sig_sig
 * Method:    newPkey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_sig_sig_newPkey
  (JNIEnv *, jobject);

/*
 * Class:     src_sig_sig
 * Method:    sigmessage
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_sig_sig_sigmessage
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     src_sig_sig
 * Method:    vefmessage
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_src_sig_sig_vefmessage
  (JNIEnv *, jobject, jlong, jstring, jstring);


JNIEXPORT jstring JNICALL Java_src_sig_sig_sigTx
  (JNIEnv *, jobject, jlong, jstring);



JNIEXPORT jstring JNICALL Java_src_sig_sig_GetBase58
  (JNIEnv *, jobject, jlong);


JNIEXPORT jstring JNICALL Java_src_sig_sig_GetPubStr
  (JNIEnv *, jobject, jlong);



/*
 * Class:     src_sig_sig
 * Method:    ExportPriHexStr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_sig_sig_ExportPriHexStr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_sig_sig
 * Method:    ImportPriHexStr
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_src_sig_sig_ImportPriHexStr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     src_sig_sig
 * Method:    ExportMnemoic
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_sig_sig_ExportMnemoic
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_sig_sig
 * Method:    ImportMnemoic
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_src_sig_sig_ImportMnemoic
  (JNIEnv *, jobject, jstring);


JNIEXPORT jstring JNICALL Java_src_sig_sig_getPubStringBase64
  (JNIEnv *, jobject, jlong);



  /*
 * Class:     src_sig_sig
 * Method:    Base64Encode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_sig_sig_Base64Encode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     src_sig_sig
 * Method:    Base64Decode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_sig_sig_Base64Decode
  (JNIEnv *, jobject, jstring);


#ifdef __cplusplus
}
#endif
#endif