/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_envelop_Envelop */

#ifndef _Included_src_envelop_Envelop
#define _Included_src_envelop_Envelop
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_envelop_Envelop
 * Method:    GetEnvelopPoint
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_src_envelop_Envelop_GetEnvelopPoint
  (JNIEnv *, jobject);

/*
 * Class:     src_envelop_Envelop
 * Method:    GetPublicString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_envelop_Envelop_GetPublicString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_envelop_Envelop
 * Method:    Encode
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_envelop_Envelop_Encode
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     src_envelop_Envelop
 * Method:    Decode
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_envelop_Envelop_Decode
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     src_envelop_Envelop
 * Method:    FreeEnvelopPoint
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_src_envelop_Envelop_FreeEnvelopPoint
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
